### PR TITLE
fix searchwindow first time use

### PR DESCRIPTION
**Pull request by viorel-m**
This patch is needed for first time users, when navi.txt does not exists

### CODE REVIEW

**Comment by viorel-m** [comment]
Also, I'm waiting myshows.ru new searchWindow implementation, I always do it by hand after every update ;)

**Comment by DiMartinoXBMC** [comment]
Thanks, I made it more stable

**Comment by DiMartinoXBMC** [comment]
what do you mean by hand? have you got it coded already?

**Comment by viorel-m** [comment]
yes, just a small change in torrents.py, the torrenter plugin call. I'm in my phone now, tomorrow will send it to you

**Comment by viorel-m** [comment]
These are my changes to torrents.py for myshows addon:

`@@ -1820,15 +1820,12 @@
             back_url = 'plugin://plugin.video.myshows/?mode=3010&sort=activate&action=add'
             return_url = 'plugin://plugin.video.myshows/?mode=3013'
             return_name = 'MyShows.ru'
-            url = 'plugin://plugin.video.torrenter/?action=search&url=%s&showKey=%s&sdata=%s' \
+            url = 'plugin://plugin.video.torrenter/?action=searchWindow&query=%s&mode=search&showKey=%s&sdata=%s' \
                   '&external=%s&back_url=%s&return_url=%s&return_name=%s%s' % \
                   (urllib.quote_plus(query), showKey, urllib.quote_plus(json.dumps(sdata)),
                    self.externals[self.stype], urllib.quote_plus(back_url),
                    urllib.quote_plus(return_url), urllib.quote_plus(return_name), silent)
-            if self.silent:
                 xbmc.executebuiltin('xbmc.RunPlugin(%s)' % (url))
-            else:
-                xbmc.executebuiltin('ActivateWindow(Videos,"%s")' % (url))
         return`

**Comment by DiMartinoXBMC** [comment]
done, a bit better

**Comment by viorel-m** [comment]
a lot better :)

**Pull request merged**
